### ISSUE TITLE
need use static_cast to be more compatible

### ISSUE THREAD

**Issue by yebangyu** [begeekmyfriend/skiplist#1]
node = malloc(sizeof(*node) + level \* sizeof(struct sk_link));

the right hand returned is void ＊. many compliers may give you an error that void ＊ can not be assigned to a variable of type skipnode＊. so, please use this instead:

node = (struct skipnode ＊)malloc(sizeof(＊node) + level ＊ sizeof(struct sk_link));

likewise, you should 

list = (struct skiplist ＊)malloc(sizeof(*list));

**Comment by begeekmyfriend** [comment]
Which kind of compiler or under which version? Less code is better for readability thank to the support of the modern compiler such as C99 -- After all, I am lazy not providing the Makefile:)
