### ISSUE TITLE
wrong header file include

### ISSUE THREAD

**Issue by yebangyu** [begeekmyfriend/skiplist#2]
in order to use gettimeofday, you should include

`<sys/time.h>`

instead of

`<time.h>` which must be included when you want to use timespec which is another tool for timing

timespec is highly recommended for you to get an accurate timing result

**Comment by begeekmyfriend** [comment]
Absolutely https://github.com/begeekmyfriend/skiplist/commit/83bbbf74ab4a4636ab9d4671b3ebc2d5aa5ced21
