### ISSUE TITLE
删除操作很慢

### ISSUE THREAD

**Issue by pyuuu** [begeekmyfriend/skiplist#8]
![image](https://user-images.githubusercontent.com/7954642/62462121-27701380-b7b9-11e9-9e11-a9e4ffc6adbc.png)
删除操作太慢了，等了5min了吧

**Comment by begeekmyfriend** [comment]
![image](https://user-images.githubusercontent.com/6031938/62505130-ed8d2480-b82d-11e9-9fb0-0dea4acc8c16.png)
不明白你的问题在哪里？
